name: Release SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 1.9.7)'
        required: true
        type: string
      publish_to_pubdev:
        description: 'Publish to pub.dev and push to main?'
        required: true
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version in pubspec.yaml
        run: |
          sed -i "s/^version: .*/version: ${{ github.event.inputs.version }}/" pubspec.yaml

      - name: Update sdkName in unleash_proxy_client_flutter.dart
        run: |
          sed -i "s/sdkName = 'unleash-flutter-sdk:[^']*'/sdkName = 'unleash-flutter-sdk:${{ github.event.inputs.version }}'/" lib/unleash_proxy_client_flutter.dart

      - name: Preserve existing CHANGELOG
        run: |
          if [ -f CHANGELOG.md ]; then cp CHANGELOG.md CHANGELOG.prev; else touch CHANGELOG.prev; fi

      - name: Generate new changelog section with git-cliff (prepend)
        uses: orhun/git-cliff-action@v4
        with:
          args: --tag v${{ github.event.inputs.version }} --prepend CHANGELOG.prev -o CHANGELOG.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b release/${{ github.event.inputs.version }}
          git add pubspec.yaml lib/unleash_proxy_client_flutter.dart CHANGELOG.md
          git commit -m "chore: release version ${{ github.event.inputs.version }}"
          git push origin release/${{ github.event.inputs.version }}

      - name: Publish to pub.dev
        if: ${{ github.event.inputs.publish_to_pubdev == 'true' }}
        run: dart pub publish --force
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}

      - name: Merge to main
        if: ${{ github.event.inputs.publish_to_pubdev == 'true' }}
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff release/${{ github.event.inputs.version }}
          git push origin main

      - name: Create version tag on main (only when publishing)
        if: ${{ github.event.inputs.publish_to_pubdev == 'true' }}
        run: |
          set -euo pipefail
          VERSION="v${{ github.event.inputs.version }}"
          git fetch origin main
          git checkout main
          git pull --ff-only origin main
          if git rev-parse -q --verify "refs/tags/${VERSION}" >/dev/null; then
            echo "Tag ${VERSION} already exists, skipping.";
          else
            git tag -a "${VERSION}" -m "Release ${VERSION}"
            git push origin "${VERSION}"
          fi

      - name: Create Pull Request (if not publishing)
        if: ${{ github.event.inputs.publish_to_pubdev != 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: release/${{ github.event.inputs.version }}
          title: "Release ${{ github.event.inputs.version }}"
          body: "Automated release PR for version ${{ github.event.inputs.version }}.\n\nPlease review the changes."
          branch: ${{ github.ref_name }}
